#!/usr/bin/env python3
"""LoogriGram: find imports of org.telegram classes that no longer exist.

Deleting a class breaks every file that still imports it - including files
where the import was ALREADY unused, which a "what did this change orphan"
check deliberately leaves alone. On 2026-09-24 that cost a compile: two
chromecast imports in MediaController had been unused since the stubs went
in, the stubs were then deleted, and nothing local noticed.

This resolves every `import org.telegram...` and `import static
org.telegram...` in the working tree against the source files: an import is
fine if some prefix of its path names an existing .java file (so nested
classes and static members resolve through their outer file) or, for a
wildcard, an existing package directory. Everything else is reported.

    python loogrigram-tools/check_dangling_imports.py

Run it after deleting any class; it takes a second.
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, 'TMessagesProj', 'src', 'main', 'java')
IMPORT = re.compile(rb'^\s*import\s+(?:static\s+)?(org\.telegram\.[\w.]+?)(\.\*)?\s*;', re.M)
# generated by the build, so never in the source tree (ResLottieMeta comes
# from buildSrc's LottieMetaPlugin)
GENERATED = ('org.telegram.messenger.R', 'org.telegram.messenger.BuildConfig',
             'org.telegram.messenger.ResLottieMeta')


def resolves(path, wildcard):
    if any(path == g or path.startswith(g + '.') for g in GENERATED):
        return True
    parts = path.split('.')
    if wildcard and os.path.isdir(os.path.join(SRC, *parts)):
        return True
    for n in range(len(parts), 1, -1):
        if os.path.isfile(os.path.join(SRC, *parts[:n]) + '.java'):
            return True
    return False


def main():
    bad = []
    for root, _, files in os.walk(os.path.join(SRC, 'org', 'telegram')):
        for f in files:
            if not f.endswith('.java'):
                continue
            path = os.path.join(root, f)
            data = open(path, 'rb').read()          # bytes: MediaController has a NUL
            for m in IMPORT.finditer(data):
                target = m.group(1).decode()
                if not resolves(target, m.group(2) is not None):
                    line = data.count(b'\n', 0, m.start()) + 1
                    bad.append('%s:%d  %s' % (os.path.relpath(path, SRC), line, target))
    for b in bad:
        print('DANGLING: ' + b)
    print('%d dangling org.telegram import(s)' % len(bad))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
